# webhook-prep
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.webhookClusterRoleBinding }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.webhookServiceAccount }}
    namespace: {{ .Values.nameSpace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.webhookClusterRole }}
  apiGroup: rbac.authorization.k8s.io
---
#cni-prep
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cniClusterRole }}
  labels:
    app: {{ .Values.cniClusterRole }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cniClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cniClusterRole }}
    namespace: {{ .Values.nameSpace }}
---
#msm-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: url-handler
subjects:
  - kind: ServiceAccount
    name: {{ .Values.nameSpace }}
    namespace: {{ .Values.nameSpace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
