# webhook-prep
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.webhookClusterRole }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - "mutatingwebhookconfigurations"
    verbs: ["*"]
---
#cni-prep
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cniClusterRole }}
  labels:
    app: {{ .Values.cniClusterRole }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
