# cni-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cniClusterRole }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.cniClusterRole }}
---
# webhook-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webhookServiceAccount }}
  namespace: {{ .Values.nameSpace }}
