---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-sidecar-cfg
  namespace: default
data:
  envoy-config.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8854
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_0
      clusters:
        - name: cluster_0
          connect_timeout: 30s
          type: STATIC
          load_assignment:
            cluster_name: cluster_0
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 554
---
apiVersion: v1
kind: Service
metadata:
  name: camera
  labels:
    run: camera
spec:
  clusterIP: 10.43.2.2
  ports:
  - name: rtsp
    port: 554
    targetPort: 8554
    protocol: TCP
  selector:
    app: camera
---
apiVersion: v1
kind: Service
metadata:
  name: cameras
  labels:
    run: cameras
spec:
  type: NodePort
  ports:
  - name: rtsp
    port: 554
    targetPort: 554
    nodePort: 30554
    protocol: TCP
  selector:
    app: camera
---
apiVersion: v1
kind: Service
metadata:
  name: camerae
  labels:
    run: camerae
spec:
  clusterIP: None
  ports:
  - name: rtsp
    port: 8854
    targetPort: 8854
    protocol: TCP
  selector:
    app: camera
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
  labels:
    app: camera
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp
          image: gilesheron/rtsp-simple-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RTSP_RTSPPORT
              value: "554"
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 554
            - name: rtp
              protocol: UDP
              containerPort: 8000
            - name: rtcp
              protocol: UDP
              containerPort: 8001

        - name: ffmpeg
          image: gilesheron/ffmpeg-image:latest
          imagePullPolicy: IfNotPresent 

        - name: envoy
          image: envoyproxy/envoy:v1.18.4
          imagePullPolicy: IfNotPresent
          args: ["-c /tmp/envoy-config.yaml"]
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8854
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: envoy-config
              mountPath: /tmp
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-sidecar-cfg
