---
apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  labels:
    app: msm-admission-webhook
spec:
  clusterIP: 10.43.0.2
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-admission-webhook
  labels:
    app: msm-admission-webhook
spec:
  selector:
    matchLabels:
      app: msm-admission-webhook
  template:
    metadata:
      labels:
        app: msm-admission-webhook
    spec:
      serviceAccount: msm-admission-webhook-sa
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
        - name: msm-admission-webhook
          image: ciscolabs/msm-admission-webhook:sidecar
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO
              value: "gilesheron"
            - name: TAG
              value: "latest"
            - name: MSM_SIDECAR
              value: "rtsp-sidecar-proxy"
            - name: IMAGE_PULL_POLICY
              value: IfNotPresent
            - name: "LOG_LVL"
              value: "DEBUG"
