---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-admission-webhook-sa
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: msm-admission-webhook-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - "mutatingwebhookconfigurations"
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: msm-admission-webhook-binding
subjects:
  - kind: ServiceAccount
    name: msm-admission-webhook-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: msm-admission-webhook-role
  apiGroup: rbac.authorization.k8s.io
