apiVersion: v1
kind: Service
metadata:
  name: msm-controller
  labels:
    msm: controller
spec:
  clusterIP: 10.96.3.1
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    msm: controller
