apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: url-handler
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-controller
  labels:
    msm: controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      msm: controller
  template:
    metadata:
      labels:
        msm: controller
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: msm-controller
          image: ciscolabs/msm-controller:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000
          env:
            - name: LOG_LVL
              value: "TRACE"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
