apiVersion: v1
kind: Service
metadata:
  name: mystream
  labels:
    app: rtsp
spec:
  clusterIP: 10.43.10.1
  ports:
    - name: rtsp
      port: 554
      targetPort: 554
      protocol: TCP
  selector:
    app: rtsp
