# rtsp-client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-client
  labels:
    rtsp: client
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      rtsp: client
  template:
    metadata:
      labels:
        rtsp: client
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-client
          image: "{{ .Values.clientImage.name }}:{{ .Values.clientImage.tag }}"
          imagePullPolicy: IfNotPresent
---
# rtsp-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server
  labels:
    app: rtsp
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      app: rtsp
  template:
    metadata:
      labels:
        app: rtsp
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-server
          image: "{{ .Values.serverImage.name }}:{{ .Values.serverImage.tag }}"
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: "{{ .Values.clientImage.name }}:{{ .Values.clientImage.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args:
            [
              "-re",
              "-stream_loop",
              "-100",
              "-i",
              "/home/docker/video.mjpeg",
              "-input_format",
              "mjpeg",
              "-pix_fmt",
              "yuvj420p",
              "-vcodec",
              "mjpeg",
              "-huffman",
              "default",
              "-f",
              "rtsp",
              "rtsp://0.0.0.0:554/mystream",
            ]
          volumeMounts:
            - mountPath: /home/docker
              name: movies
      volumes:
        - name: movies
          hostPath:
            path: /home/docker
